import "./globals.css";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "funroad",
  description: "Generated by create next app",
};

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dmSans.className}`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
